version: '3.12'

services:
    postgres:
        container_name: PostgreSQL
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123456789
            - POSTGRES_USER=postgres
            - POSTGRES_DB=links
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        env_file: ./user_links_api/.env
        ports:
            - 5432:5432
        restart: unless-stopped

    web:
        container_name: Django
        build:  ./user_links_api
        restart: always
        volumes:
            - postgres:/code/postgres
        command: bash -c "pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        depends_on:
            - postgres

volumes:
    postgres:
