# Generated by Django 5.0 on 2024-11-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('url_page', models.CharField(unique=True)),
                ('kind_link', models.CharField(choices=[('WEBSITE', 'WEBSITE'), ('BOOK', 'BOOK'), ('ARTICLE', 'ARTICLE'), ('MUSIC', 'MUSIC'), ('VIDEO', 'VIDEO')], default='WEBSITE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
