# Generated by Django 5.0 on 2024-11-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linksmodel',
            old_name='short_description',
            new_name='description',
        ),
    ]
