# Generated by Django 5.0 on 2024-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_short_description_linksmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='url_page',
            field=models.URLField(unique=True),
        ),
    ]
