# Generated by Django 5.0 on 2024-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
