# Generated by Django 5.0 on 2024-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_linksmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='images/'),
        ),
    ]
