# Generated by Django 5.0 on 2024-11-13 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_linksmodel_url_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='title',
            field=models.CharField(),
        ),
    ]
