# Generated by Django 5.0 on 2024-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_linksmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='url_page',
            field=models.URLField(max_length=500),
        ),
    ]
