# Generated by Django 5.0 on 2024-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_collectionmodel_delete_сollectionmodel'),
        ('links', '0004_alter_linksmodel_description_alter_linksmodel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='collection',
            field=models.ManyToManyField(to='collections.collectionmodel'),
        ),
    ]
