# Generated by Django 5.0 on 2024-11-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_collectionmodel_delete_сollectionmodel'),
        ('links', '0005_linksmodel_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='collection',
            field=models.ManyToManyField(null=True, to='collections.collectionmodel'),
        ),
    ]
