# Generated by Django 5.0 on 2024-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_linksmodel_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='url_page',
            field=models.URLField(),
        ),
    ]
