# Generated by Django 5.0 on 2024-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сollection',
            new_name='СollectionModel',
        ),
    ]
